# Site wide configuration

title: Viva La Vida 
locale: en_US # For Open Graph only?
url: 


# Jekyll configuration

permalink:   /blog/:year/:month/:day/:title
#markdown:    kramdown
markdown:    redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

redcarpet:
  extensions: ["strikethrough", "tables", "no_intra_emphasis", "autolink"]
  #extensions: ["strikethrough", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "footnotes"]
#kramdown:
#  auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
#  toc_levels: 1..6
#  use_coderay: false

# Site owner
owner:
  name: OopsMonk
  avatar: bio-oopsmonk.jpg
  bio: "I'm happiest when I am studying new technologies or discovering new things. Challenges make me struggle but stronger."
  email: 
  disqus-shortname: oopsmonk
  twitter: oopsmonkTW
  facebook: #username
  google:
    plus: #username
    analytics: UA-59507590-1
    verify: 
    ad-client: ca-pub-9804446043357042
    ad-slot: 6851826707
  bing-verify: 
  github: oopsmonk
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: oopsmonk
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
