baseURL: https://oopsmonk.github.io/
languageCode: en-us
title: oopsmonk
paginate: 7
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: 364511140

minify:
  disableXML: true
  minifyOutput: true

# for search function
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Viva La Vida
  description: ""
  keywords: [Blog, Portfolio]
  author: oopsmonk
  # author: ["Me", "You"] # multiple authors
  images: ["images/bio-oopsmonk.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

#  assets:
#    # disableHLJS: true # to disable highlight.js
#    # disableFingerprinting: true
#    favicon: "<link / abs url>"
#    favicon16x16: "<link / abs url>"
#    favicon32x32: "<link / abs url>"
#    apple_touch_icon: "<link / abs url>"
#    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
#    icon: /images/bio-oopsmonk.jpg
#    iconHeight: 35

  # profile-mode
  profileMode:
    # enabled: true # needs to be explicitly set
    title: "like making things simple and keep learning"
    subtitle: "Father ★ Software Engineer ★ Home Baker"
    imageUrl: "/images/bio-oopsmonk.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: oopsmonk
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Archives
        url: archives

  # home-info mode
  homeInfoParams:
    enabled: true # needs to be explicitly set
    title: "like making things simple and keep learning"
    Content: "Father ★ Software Engineer ★ Home Baker"
  socialIcons:
    - name: twitter
      url: "https://twitter.com/oops_monk"
    - name: github
      url: "https://github.com/oopsmonk"
    - name: linkedin 
      url: "https://www.linkedin.com/in/oopsmonk"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/oopsmonk/oopsmonk.github.io/issues"
    Text: "Suggest Changes" # edit text
    appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
#   - identifier: categories
#     name: Categories
#     url: /categories/
#     weight: 15
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 25
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
